services:
  - type: web
    name: jt-dashboard-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
      - key: OPENAI_API_KEY
        sync: false
    domains:
      - jt-dashboard-api.onrender.com